### ISSUE TITLE
Function is not defined error message.

### ISSUE THREAD

**Issue by ryankerschner-trimble** [trimble-oss/openapi-spectral-rules#6]
Hello,

There appears to be an issue when attempting to run the lint command. 

I followed the instructions that are provided on the main page for these spectral rules. This was working last week. Now it presents the following error message
![image](https://user-images.githubusercontent.com/129630479/229368846-03f20a9c-218f-428b-85fd-d3ffdb9c9fd0.png)

**Comment by jbend** [comment]
This is now fixed. A bug was introduced recently with the enhancement of an existing rule. We'll be looking to add a better testing and release process in the near future
